### ISSUE TITLE
No "Precise location" notification improvement

### ISSUE THREAD

**Issue by HankAviator** [kmark/NoMapTips#1]
With the latest NoMapTips module

**Comment by kmark** [comment]
Is this the same or similar report as this [issue posted on XDA](http://forum.xda-developers.com/showpost.php?p=60965104&postcount=124)?

**Comment by HankAviator** [comment]
Not really bud:
I'm on 5.0.1, and I simply upgraded the map to 9.9.0. I think it's just due to the version differences. :smile: 
PS: I get the same dialog.

**Comment by kmark** [comment]
Does this dialog appear only when you tap location accuracy tips?

**Comment by HankAviator** [comment]
Yup

**Comment by kmark** [comment]
Then it looks to be the same occurrence as the XDA user is describing. NoMapTips is no longer required after Maps 9.8.0 as Google provides a "never" option to those dialogs so you will not be bothered again. The only time those dialogs (without a never option) would show is if you manually tap Location accuracy tips.

**Comment by HankAviator** [comment]
Nope, when I tap _my location_ button, it brings out the exact dialog that I tap _Location accuracy_. I am only provided with two options: Yes and No.

**Comment by kmark** [comment]
That's odd. I cannot reproduce it. What does the dialog suggest? WiFi?

**Comment by HankAviator** [comment]
It suggests me to enable GPS (I was on Battery saving location mode)
![screenshot_2015-06-01-19-17-47](https://cloud.githubusercontent.com/assets/8069557/7911747/859407d4-0893-11e5-831e-f712c4653143.png)

**Comment by kmark** [comment]
Well, I could make it disable this tip but I imagine Maps is going to have a difficult time locating you without access to the GPS. The primary thing NoMapTips was aimed at was the WiFi tips which Google didn't need to find you.

**Comment by HankAviator** [comment]
Ok! If there's a workaround for this I'd be grateful!

**Comment by kmark** [comment]
I could theoretically update NoMapTips to remove the GPS dialog but it would not fix the issue with Maps "pretending" to not locate you. Using the app without WiFi is one thing (as I often do) but using it to locate you without GPS or high-accuracy location is another. :wink:

**Comment by HankAviator** [comment]
aha, though it does locate me with the best effort it can get - WiFi positioning.
Thank you very much for this cute module for hassle-free using experience! ;)

**Comment by kmark** [comment]
My pleasure. If you ever feel the itch to improve NoMapTips for your use the `NoMapTips.java` file should point you in the right direction.

**Comment by HankAviator** [comment]
thanks! But I know nothing about java so I'd only be an experienced user :smile:

**Comment by HankAviator** [comment]
Hi Mark sorry but I have no clue how to maneuver (editing, compiling) to fit my need despite the well documented codes. I know it's not proper to ask but ... Would you be willing to help to make the _improvement_? Thanks :)

**Comment by kmark** [comment]
Hello, Hank. Unfortunately I do not have the time to spend on updating NoMapTips right now for additional uses. Luckily the ["never" option](https://i.imgur.com/IZwbvIn.png) is now available which makes this module in its current state no longer useful.
