### ISSUE TITLE
Support for Tinder

### ISSUE THREAD

**Issue by keunes** [kmark/NoMapTips#2]
I know, which pethatic person uses tinder? But still, it's a great time-waster on the train. Obviously, WiFi localisation doesn't make sense here but the app keeps bugging me every second (which is worse than on every app start) asking me to turn on WiFi, detailed localisation and sharing my location with Google.

Would be great if you guys somehow also managed to support tinder's requests ;)

**Comment by kmark** [comment]
Unfortunately this is out of scope for NoMapTips. Perhaps the ["never" option](https://i.imgur.com/IZwbvIn.png) is now available in Tinder as well? Thanks for the suggestion!
