### ISSUE TITLE
Keep 'avoid tolls' as default option 

### ISSUE THREAD

**Issue by terrorist96** [kmark/NoMapTips#3]
Could this feature be added to this module, please? If not, a separate module that accomplishes this. 

Thanks! 
https://www.reddit.com/r/xposed/comments/3plu44/request_keep_avoid_tolls_as_default_option_in/

**Comment by kmark** [comment]
Unfortunately this is out of scope for NoMapTips. Thanks for the suggestion.

**Comment by terrorist96** [comment]
So maybe a separate module that accomplishes this? If not, thanks anyway.

**Comment by kmark** [comment]
A separate module could probably accomplish this. Unfortunately I do not have the time to work on it at the moment.
